#!/bin/bash
# CubeStack 虚拟机私有网桥(privbr0)宿主机网络初始化脚本（可直接落地）
# ============================================================
# 解决痛点: 虚拟机网段 10.244.0.0/16(privbr0) 与 物理Worker网段 10.66.1.0/24 跨二层非直连,
#           物理Worker 无法配置指向 10.244.0.0/16 的静态路由(下一跳非直连,路由不生效)。
# 方案:     虚拟机出网 SNAT 伪装 + 宿主机本地回程静态路由,双向互通,零改动物理机网络。
#
#   正向流量: VM(10.244.x) → 宿主机转发 → SNAT 成宿主机物理 IP(${HOST_PHYS_IP}, 自动检测) → 物理Worker(10.66.1.x)
#   回程流量: Worker 回包给宿主机物理 IP(${HOST_PHYS_IP}) → conntrack 反解回 10.244.x → 回程路由(10.244/16 dev privbr0) → VM
#
# 幂等: 可重复执行,重复运行仅提示"已存在"。开机自启由 systemd oneshot 兜底,
#       不依赖 iptables-persistent(离线环境也可靠)。
#
# 依赖: iproute2 / iptables / kmod / procps / systemd (Ubuntu 均默认自带)
#       缺失时脚本自动 apt-get 安装;离线环境可用 SKIP_DEPS=1 跳过安装(仅告警)
#
# 用法:  sudo ./setup-vm-network.sh
# 数据源: config/cluster.conf(BRIDGE/BRIDGE_IP/VM_SUBNET/HOST_PHYS_IP/PHYS_WORKER_NET)
# 环境变量覆盖: 同名变量(如 BRIDGE=custom) 与 SKIP_DEPS
# ============================================================

set -euo pipefail

# ==================== 加载统一配置 ====================
# say/ok/warn/err 等函数来自 lib-common.sh
# shellcheck source=lib-common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib-common.sh"
load_config

# 兜底默认(仅在配置文件缺失时生效)
BRIDGE="${BRIDGE:-privbr0}"
BRIDGE_IP="${BRIDGE_IP:-10.244.0.1}"
VM_SUBNET="${VM_SUBNET:-10.244.0.0/16}"
BRIDGE_PREFIX="${BRIDGE_PREFIX:-${VM_SUBNET#*/}}"
# HOST_PHYS_IP 由 lib-common load_config 统一提供(留空自动检测), 不再本地设置
PHYS_WORKER_NET="${PHYS_WORKER_NET:-10.66.1.0/24}"

SYSCTL_CONF="/etc/sysctl.d/99-k8s-forward.conf"
SVC_NAME="privbr0-net.service"
BOOTSTRAP="/usr/local/sbin/privbr0-net-bootstrap.sh"

# ==================== 前置检查 ====================
[ "$(id -u)" -eq 0 ] || { err "需要 root 权限,请执行: sudo $0"; exit 1; }

# ==================== 依赖检查 ====================
# 本脚本依赖: iproute2 / iptables / kmod / procps / systemd (Ubuntu 默认自带)
# 缺失时自动 apt-get 安装;离线环境 SKIP_DEPS=1 跳过安装(仅告警,缺必需命令再报错)
pkg_for() {
    case "$1" in
        ip)        echo iproute2 ;;
        iptables)  echo iptables ;;
        sysctl)    echo procps ;;
        modprobe)  echo kmod ;;
        systemctl) echo systemd ;;
        *)         echo "$1" ;;
    esac
}
MISSING=""
for bin in ip iptables sysctl modprobe systemctl; do
    command -v "${bin}" >/dev/null 2>&1 || MISSING="${MISSING} ${bin}"
done
if [ -n "${MISSING}" ]; then
    echo -e "\033[33m⚠ 检测到缺失命令:${MISSING}\033[0m"
    if [ "${SKIP_DEPS:-0}" = "1" ]; then
        warn "SKIP_DEPS=1: 跳过依赖安装,若后续命令失败请手动安装"
    else
        PKGS=""
        for bin in ${MISSING}; do PKGS="${PKGS} $(pkg_for "${bin}")"; done
        say "尝试安装依赖: apt-get install -y${PKGS}"
        DEBIAN_FRONTEND=noninteractive apt-get install -y ${PKGS} >/dev/null 2>&1 || {
            echo -e "\033[31m【错误】依赖安装失败。请手动执行: sudo apt-get install -y${PKGS}\n      (离线环境请提前安装,或 SKIP_DEPS=1 跳过安装)\033[0m"; exit 1; }
    fi
    for bin in ip iptables sysctl modprobe; do
        command -v "${bin}" >/dev/null 2>&1 || { echo -e "\033[31m【错误】必需命令缺失: ${bin},请安装后重试\033[0m"; exit 1; }
    done
fi
ok "依赖检查通过(iproute2/iptables/kmod/procps/systemd)"

# ==================== 1. 内核参数 ====================
say "加载内核模块 overlay / br_netfilter / bridge ..."
modprobe overlay      2>/dev/null || warn "modprobe overlay 失败(内核可能已内建,可忽略)"
modprobe br_netfilter 2>/dev/null || warn "modprobe br_netfilter 失败: 若需 iptables 过滤/SNAT 网桥流量,请确认内核支持"
modprobe bridge       2>/dev/null || warn "modprobe bridge 失败: 创建网桥需要内核 bridge 模块"

# 容错 sysctl: 内核不存在的键仅告警,不中断脚本(如老内核无 net.ipv4.route_localnet)
sysctl_set() { # <key=value> [描述]
    local kv="$1" desc="${2:-}"
    if sysctl -w "${kv}" >/dev/null 2>&1; then
        ok "内核参数 ${kv}"
    else
        warn "无法设置 ${kv}${desc:+ — ${desc}},已跳过"
    fi
}

# 临时生效
sysctl_set "net.ipv4.ip_forward=1"
sysctl_set "net.bridge.bridge-nf-call-iptables=1" "需 br_netfilter 模块"
sysctl_set "net.ipv4.route_localnet=1" "可选参数,内核>=4.5才有,本方案不依赖"

# 永久固化: 仅写入内核实际支持的键
{
    echo "# Generated by ${0}"
    echo "net.ipv4.ip_forward=1"
    echo "net.bridge.bridge-nf-call-iptables=1"
    echo "net.bridge.bridge-nf-call-ip6tables=1"
} > "${SYSCTL_CONF}"
# route_localnet 支持才追加到固化文件(老内核写进去会让 sysctl -p 报错)
sysctl -w net.ipv4.route_localnet=1 >/dev/null 2>&1 && echo "net.ipv4.route_localnet=1" >> "${SYSCTL_CONF}"
sysctl -p "${SYSCTL_CONF}" >/dev/null 2>&1 || warn "sysctl -p 加载 ${SYSCTL_CONF} 有告警(不影响已生效参数)"
ok "内核参数已固化: ${SYSCTL_CONF}"

# ==================== 2. 创建私有网桥 ====================
say "创建私有网桥 ${BRIDGE} (${BRIDGE_IP}/${BRIDGE_PREFIX}) ..."
if [ ! -d "/sys/class/net/${BRIDGE}" ]; then
    if ! ip link add name "${BRIDGE}" type bridge 2>/dev/null; then
        echo -e "\033[31m【错误】创建网桥 ${BRIDGE} 失败。请确认:\n ① 内核支持 bridge 模块: sudo modprobe bridge\n ② 已安装 iproute2: sudo apt-get install -y iproute2 bridge-utils\n 或改用 VM_NET_MODE=net 挂 libvirt 网络\033[0m"
        exit 1
    fi
    ok "网桥 ${BRIDGE} 已创建"
fi
if ! ip -4 addr show dev "${BRIDGE}" | grep -q "${BRIDGE_IP}/"; then
    ip addr add "${BRIDGE_IP}/${BRIDGE_PREFIX}" dev "${BRIDGE}"
fi
ip link set "${BRIDGE}" up
ok "网桥就绪: ${BRIDGE}=$(ip -4 addr show dev "${BRIDGE}" | awk '/inet /{print $2}' | tr '\n' ' ')"

# ==================== 3. 回程路由（反向路由回溯）====================
ip route replace "${VM_SUBNET}" dev "${BRIDGE}" proto static
ok "回程路由: ${VM_SUBNET} dev ${BRIDGE}"

# ==================== 4. 精准 SNAT 伪装 ====================
say "配置 SNAT: ${VM_SUBNET} → ${PHYS_WORKER_NET} 伪装为 ${HOST_PHYS_IP} ..."
if iptables -t nat -C POSTROUTING -s "${VM_SUBNET}" -d "${PHYS_WORKER_NET}" -j SNAT --to-source "${HOST_PHYS_IP}" 2>/dev/null; then
    ok "SNAT 规则已存在,跳过"
else
    # -I 插入首位,确保优先于 libvirt 默认网络的 MASQUERADE
    iptables -t nat -I POSTROUTING -s "${VM_SUBNET}" -d "${PHYS_WORKER_NET}" -j SNAT --to-source "${HOST_PHYS_IP}"
    ok "SNAT 规则已添加(插入 POSTROUTING 首位)"
fi

# 放行网桥转发(开启 bridge-nf-call-iptables 后 VM 流量会走 FORWARD 链,必须放行)
iptables -C FORWARD -i "${BRIDGE}" -j ACCEPT 2>/dev/null || iptables -A FORWARD -i "${BRIDGE}" -j ACCEPT
iptables -C FORWARD -o "${BRIDGE}" -j ACCEPT 2>/dev/null || iptables -A FORWARD -o "${BRIDGE}" -j ACCEPT
iptables -P FORWARD ACCEPT 2>/dev/null || true
ok "FORWARD 链放行策略就绪"

# ==================== 5. 开机自启固化 ====================
# 5.1 生成开机启动脚本(网桥+回程路由+SNAT,全部幂等)
cat > "${BOOTSTRAP}" <<EOF
#!/bin/bash
# Generated by ${0} — 开机自启: 恢复 ${BRIDGE} 网桥/回程路由/SNAT
set -euo pipefail
BRIDGE='${BRIDGE}'
BRIDGE_IP='${BRIDGE_IP}'
BRIDGE_PREFIX='${BRIDGE_PREFIX}'
VM_SUBNET='${VM_SUBNET}'
HOST_PHYS_IP='${HOST_PHYS_IP}'
PHYS_WORKER_NET='${PHYS_WORKER_NET}'

modprobe br_netfilter 2>/dev/null || true
sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1 || true
sysctl -w net.ipv4.route_localnet=1 >/dev/null 2>&1 || true

# 1) 恢复网桥
if [ ! -d "/sys/class/net/\${BRIDGE}" ]; then
    ip link add name "\${BRIDGE}" type bridge
fi
ip addr flush dev "\${BRIDGE}" 2>/dev/null || true
ip addr add "\${BRIDGE_IP}/\${BRIDGE_PREFIX}" dev "\${BRIDGE}"
ip link set "\${BRIDGE}" up

# 2) 回程路由
ip route replace "\${VM_SUBNET}" dev "\${BRIDGE}" proto static

# 3) 精准 SNAT
iptables -t nat -C POSTROUTING -s "\${VM_SUBNET}" -d "\${PHYS_WORKER_NET}" -j SNAT --to-source "\${HOST_PHYS_IP}" 2>/dev/null || \
    iptables -t nat -I POSTROUTING -s "\${VM_SUBNET}" -d "\${PHYS_WORKER_NET}" -j SNAT --to-source "\${HOST_PHYS_IP}"

# 4) 放行网桥转发
iptables -C FORWARD -i "\${BRIDGE}" -j ACCEPT 2>/dev/null || iptables -A FORWARD -i "\${BRIDGE}" -j ACCEPT
iptables -C FORWARD -o "\${BRIDGE}" -j ACCEPT 2>/dev/null || iptables -A FORWARD -o "\${BRIDGE}" -j ACCEPT
iptables -P FORWARD ACCEPT 2>/dev/null || true

exit 0
EOF
chmod +x "${BOOTSTRAP}"

# 5.2 安装 systemd 自启单元(早于 libvirtd 启动,保证 VM 挂网桥前桥已就绪)
cat > "/etc/systemd/system/${SVC_NAME}" <<EOF
[Unit]
Description=CubeStack VM private bridge (${BRIDGE}) network bootstrap
After=network-pre.target
Wants=network-pre.target
Before=network.target libvirtd.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=${BOOTSTRAP}

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable "${SVC_NAME}" >/dev/null 2>&1 || true
systemctl start "${SVC_NAME}"
ok "开机自启已启用: ${SVC_NAME} → ${BOOTSTRAP}"

# ==================== 6.（可选）iptables 规则持久化 ====================
# systemd 自启已兜底;此处仅锦上添花。离线环境 apt 可能失败,失败不影响整体
if command -v netfilter-persistent >/dev/null 2>&1; then
    netfilter-persistent save >/dev/null 2>&1 && ok "iptables 规则已通过 netfilter-persistent 保存" || warn "netfilter-persistent save 失败(自启已兜底)"
elif command -v apt-get >/dev/null 2>&1; then
    say "未安装 iptables-persistent,尝试安装(离线环境可跳过,由 systemd 自启兜底) ..."
    DEBIAN_FRONTEND=noninteractive apt-get install -y iptables-persistent >/dev/null 2>&1 \
        && netfilter-persistent save >/dev/null 2>&1 \
        && ok "iptables-persistent 安装并保存成功" \
        || warn "iptables-persistent 安装/保存失败,已由 systemd 自启兜底"
fi

# ==================== 汇总 ====================
echo "============================================="
echo -e "\033[32m✅ 宿主机网络配置完成\033[0m"
echo "  网桥:       ${BRIDGE} = ${BRIDGE_IP}/${BRIDGE_PREFIX}"
echo "  回程路由:   ${VM_SUBNET} dev ${BRIDGE}"
echo "  SNAT:       ${VM_SUBNET} → ${PHYS_WORKER_NET} 伪装为 ${HOST_PHYS_IP}"
echo "  开机自启:   ${SVC_NAME}"
echo "  下一步:     sudo ./scripts/verify-vm-network.sh 验证连通性"
echo "  之后:       ./scripts/create-libvirt-vm.sh cubestack-k8s-master01 16 8 50 <MAC> 10.244.1.11"
echo "============================================="
