#!/bin/bash
# ============================================================
# 从 cluster.conf 自动生成并同步节点 hosts 解析(宿主机)
# 生成: /etc/hosts + /etc/dnsmasq.hosts
#   k8s-api.nova.local → 宿主机 API 地址
#   所有 master/worker 节点 hostname → IP
# 幂等: 自动移除旧的 nova-k8s-* / mxgpu-* 条目再追加新条目
# 用法: sudo ./sync-hosts.sh
# 数据源: deployments/config/cluster-${CLUSTER_NAME}.conf
# ============================================================
set -euo pipefail

# shellcheck source=lib-common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib-common.sh"
load_config

[ "$(id -u)" -eq 0 ] || { err "需要 root: sudo $0"; exit 1; }

API_IP="${APISERVER_ADDRESS:-${HOST_PHYS_IP:-10.66.3.37}}"
API_DOMAIN="${APISERVER_DOMAIN:-k8s-api.nova.local}"

say "API 解析: ${API_DOMAIN} → ${API_IP}"

# 收集所有节点 hostname→ip
NODE_ENTRIES=""
for line in "${NODES[@]:-}"; do
    [ -z "${line}" ] && continue
    IFS=, read -r role hostname ip mac mem cpu disk user pw <<<"${line}"
    NODE_ENTRIES="${NODE_ENTRIES}
${ip}     ${hostname}"
done

# 生成 hosts 条目(带集群标识分隔)
HOSTS_BLOCK="# >>> cubestack-cluster (auto-generated by sync-hosts.sh)
${API_IP}          ${API_DOMAIN}${NODE_ENTRIES}
# <<< cubestack-cluster"

# ---- 更新 /etc/hosts ----
# 1. 删除旧的 cubestack 集群块
sed -i '/# >>> cubestack-cluster/,/# <<< cubestack-cluster/d' /etc/hosts
# 2. 删除旧的 nova-k8s-master / nova-k8s-node / mxgpu 裸条目
sed -i -E '/nova-k8s-(master|node)/d; /mxgpu-[0-9]/d; /k8s-api\.nova\.local/d' /etc/hosts
# 3. 追加新块
echo "${HOSTS_BLOCK}" >> /etc/hosts
ok "已更新 /etc/hosts (${#NODES[@]} 节点)"

# ---- 更新 /etc/dnsmasq.hosts ----
if [ -f /etc/dnsmasq.hosts ]; then
    sed -i '/# >>> cubestack-cluster/,/# <<< cubestack-cluster/d' /etc/dnsmasq.hosts
    sed -i -E '/nova-k8s-(master|node)/d; /mxgpu-[0-9]/d; /k8s-api\.nova\.local/d' /etc/dnsmasq.hosts
    echo "${HOSTS_BLOCK}" >> /etc/dnsmasq.hosts
    systemctl restart dnsmasq 2>/dev/null || true
    ok "已更新 /etc/dnsmasq.hosts + 重启 dnsmasq"
else
    warn "未找到 /etc/dnsmasq.hosts,跳过"
fi

echo "---------------------------------------------"
getent hosts "${API_DOMAIN}" && echo "✅ ${API_DOMAIN} 解析正常"