all:
  vars:
    ansible_become: true
    ansible_become_method: sudo

kube_control_plane:
  hosts:
    cubestack-k8s-master01:
      ansible_host: 192.168.122.11
      ip: 192.168.122.11            # K8s 内部通信使用的 IP
      access_ip: 192.168.122.11      # API Server 对外暴露的 IP`
      ansible_user: ubuntu
    cubestack-k8s-master02:
      ansible_host: 192.168.122.12
      ip: 192.168.122.12            # K8s 内部通信使用的 IP
      access_ip: 192.168.122.12      # API Server 对外暴露的 IP`
      ansible_user: ubuntu
    cubestack-k8s-master03:
      ansible_host: 192.168.122.13
      ip: 192.168.122.13            # K8s 内部通信使用的 IP
      access_ip: 192.168.122.13      # API Server 对外暴露的 IP`
      ansible_user: ubuntu

etcd:
  children:
    kube_control_plane:

kube_node:
  hosts:
    mxgpu-1-232:
      ansible_host: 10.66.1.232
      ip: 10.66.1.232                # K8s 内部通信 IP
      access_ip: 10.66.1.232         # 该节点对外服务 IP
      ansible_user: ubuntu
    mxgpu-1-147:
      ansible_host: 10.66.1.147
      ip: 10.66.1.147
      access_ip: 10.66.1.147
      ansible_user: ubuntu
    mxgpu-1-152:
      ansible_host: 10.66.1.152
      ip: 10.66.1.152
      access_ip: 10.66.1.152
      ansible_user: ubuntu
    mxgpu-1-154:
      ansible_host: 10.66.1.154
      ip: 10.66.1.154
      access_ip: 10.66.1.154
      ansible_user: ubuntu
    mxgpu-1-165:
      ansible_host: 10.66.1.165
      ip: 10.66.1.165
      access_ip: 10.66.1.165
      ansible_user: ubuntu
    mxgpu-1-166:
      ansible_host: 10.66.1.166
      ip: 10.66.1.166
      access_ip: 10.66.1.166
      ansible_user: ubuntu
    mxgpu-1-167:
      ansible_host: 10.66.1.167
      ip: 10.66.1.167
      access_ip: 10.66.1.167
      ansible_user: ubuntu
    mxgpu-1-168:
      ansible_host: 10.66.1.168
      ip: 10.66.1.168
      access_ip: 10.66.1.168
      ansible_user: ubuntu
    mxgpu-1-169:
      ansible_host: 10.66.1.169
      ip: 10.66.1.169
      access_ip: 10.66.1.169
      ansible_user: ubuntu

k8s_cluster:
  children:
    kube_control_plane:
    kube_node:
