apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cubestack-bmc-exporter.fullname" . }}-bmc-credentials
  labels:
    {{- include "cubestack-bmc-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ required "bmc.username is required" .Values.bmc.username | quote }}
  password: {{ required "bmc.password is required" .Values.bmc.password | quote }}
