apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cubestack-bmc-exporter.fullname" . }}-idrac-config
  labels:
    {{- include "cubestack-bmc-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  idrac.yml: |
    address: 0.0.0.0
    port: 9348
    timeout: {{ .Values.idracExporter.config.timeout }}
    hosts:
    {{- range .Values.bmc.hosts }}
      "{{ . }}":
        username: {{ $.Values.bmc.username | quote }}
        password: {{ $.Values.bmc.password | quote }}
    {{- end }}
    metrics:
    {{- range $name, $enabled := .Values.idracExporter.config.metrics }}
      {{ $name }}: {{ $enabled }}
    {{- end }}
