apiVersion: v1
kind: Service
metadata:
  name: {{ include "cubestack-bmc-exporter.fullname" . }}-bmc-oem-exporter
  labels:
    {{- include "cubestack-bmc-exporter.componentLabels" (dict "component" "bmc-oem-exporter" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
spec:
  selector:
    {{- include "cubestack-bmc-exporter.componentLabels" (dict "component" "bmc-oem-exporter" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
  ports:
    - name: metrics
      port: 9622
      targetPort: 9622
