apiVersion: v1
kind: Service
metadata:
  name: {{ include "cubestack-bmc-exporter.fullname" . }}-idrac-exporter
  labels:
    {{- include "cubestack-bmc-exporter.componentLabels" (dict "component" "idrac-exporter" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
spec:
  selector:
    {{- include "cubestack-bmc-exporter.componentLabels" (dict "component" "idrac-exporter" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
  ports:
    - name: metrics
      port: 9348
      targetPort: 9348
