annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/perses/helm-charts
    - name: Upstream Project
      url: https://github.com/perses/perses
apiVersion: v2
appVersion: v0.54.0
description: Perses helm chart
icon: https://avatars.githubusercontent.com/u/77209215?s=200&v=4
keywords:
- monitoring
- metric
- dashboarding
- prometheus
name: perses
sources:
- https://github.com/perses/perses
type: application
version: 0.23.2
