#!/bin/bash
# ============================================================
# ⚠ 已废弃(deprecated): registry 已由 MetalLB VIP / NodePort 直连暴露, 无需宿主机
#   级 DNAT。本脚本保留仅作兼容, 不再由 deploy-registry.sh 调用; 集群外访问请直接用
#   MetalLB VIP 或 NodePort(跨网段经路由/防火墙放行, 而非宿主机 NAT 转发)。
# 历史用途: 将 宿主机物理IP:REGISTRY_PORT 的入站流量 DNAT 到 MetalLB VIP(REGISTRY_IP):REGISTRY_PORT,
#   使物理网(10.66.x)上的机器能 docker push registry.cubestack.io:5000/xxx。
#   同时写 PREROUTING(外部网卡流量) + OUTPUT(宿主机本机 push) 两条规则, 幂等。
#   持久化: 安装 systemd 单元, 重启后自动重建规则。
# 用法: ./setup-registry-expose.sh [--add|--delete]   (默认 --add)
# 数据源: config/cluster.conf (HOST_PHYS_IP / REGISTRY_ENABLED / REGISTRY_IP / REGISTRY_PORT)
# ============================================================
set -euo pipefail

# shellcheck source=lib-common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../lib-common.sh"
load_config

ACTION="${1:---add}"
# REGISTRY_ENABLED 兼容 1/true/yes/on(TOGGLE 导出可能为 "true" 字符串)
case "${REGISTRY_ENABLED:-0}" in
    1|true|yes|on) ;;
    *) warn "REGISTRY_ENABLED!=1, 跳过端口转发(集群内 registry 默认不部署)"; exit 0 ;;
esac

# 依据暴露方式决定 DNAT 目标(集群外 push 的落点):
#   loadbalancer → MetalLB 固定 VIP:REGISTRY_PORT
#   nodeport     → 第一个节点的 NodePort(kube-proxy 自动转发到 registry pod, 不依赖 MetalLB)
REGISTRY_FORWARD_TARGET=""
case "${REGISTRY_SERVICE_TYPE:-loadbalancer}" in
    nodeport)
        [ -n "${REGISTRY_NODEPORT:-}" ] || { err "未配置 REGISTRY_NODEPORT"; exit 1; }
        for line in "${NODES[@]:-}"; do
            [ -z "${line}" ] && continue
            node_parse "${line}"
            [ -n "${NODE_IP}" ] && { REGISTRY_FORWARD_TARGET="${NODE_IP}:${REGISTRY_NODEPORT}"; break; }
        done
        ;;
    *)
        [ -n "${REGISTRY_IP:-}" ] && [ -n "${REGISTRY_PORT:-}" ] || { err "未配置 REGISTRY_IP/REGISTRY_PORT"; exit 1; }
        REGISTRY_FORWARD_TARGET="${REGISTRY_IP}:${REGISTRY_PORT}"
        ;;
esac
[ -n "${REGISTRY_FORWARD_TARGET}" ] || { err "无法确定 registry 转发目标(检查 REGISTRY_SERVICE_TYPE/NODES)"; exit 1; }
# 外部统一入口端口(集群外 push 用)
EXTERNAL_PORT="${REGISTRY_PORT:-5000}"

# 需 root
[ "$(id -u)" -eq 0 ] || { err "需要 root 权限: sudo $0 ${ACTION}"; exit 1; }

UNIT="cubestack-registry-forward"
UNIT_FILE="/etc/systemd/system/${UNIT}.service"
FORWARD_SCRIPT="/usr/local/bin/${UNIT}.sh"

# 规则体(写入 /usr/local/bin 的 forward 脚本 + systemd 单元引用)
forward_script_body() {
    cat <<EOF
#!/bin/bash
# Auto-generated by setup-registry-expose.sh — 重启后重建 registry 对外 DNAT(勿手工编辑)
# ${HOST_PHYS_IP}:${EXTERNAL_PORT} → ${REGISTRY_FORWARD_TARGET}
set -e
action="\${1:---add}"
if [ "\${action}" = "--delete" ]; then
    iptables -t nat -D PREROUTING -d ${HOST_PHYS_IP} -p tcp --dport ${EXTERNAL_PORT} -j DNAT --to-destination ${REGISTRY_FORWARD_TARGET} 2>/dev/null || true
    iptables -t nat -D OUTPUT -d ${HOST_PHYS_IP} -p tcp --dport ${EXTERNAL_PORT} -j DNAT --to-destination ${REGISTRY_FORWARD_TARGET} 2>/dev/null || true
else
    iptables -t nat -C PREROUTING -d ${HOST_PHYS_IP} -p tcp --dport ${EXTERNAL_PORT} -j DNAT --to-destination ${REGISTRY_FORWARD_TARGET} 2>/dev/null || \
        iptables -t nat -A PREROUTING -d ${HOST_PHYS_IP} -p tcp --dport ${EXTERNAL_PORT} -j DNAT --to-destination ${REGISTRY_FORWARD_TARGET}
    iptables -t nat -C OUTPUT -d ${HOST_PHYS_IP} -p tcp --dport ${EXTERNAL_PORT} -j DNAT --to-destination ${REGISTRY_FORWARD_TARGET} 2>/dev/null || \
        iptables -t nat -A OUTPUT -d ${HOST_PHYS_IP} -p tcp --dport ${EXTERNAL_PORT} -j DNAT --to-destination ${REGISTRY_FORWARD_TARGET}
fi
exit 0
EOF
}

case "${ACTION}" in
    --add)
        say "添加宿主机 registry 端口转发: ${HOST_PHYS_IP}:${EXTERNAL_PORT} → ${REGISTRY_FORWARD_TARGET} ..."
        # ★ 清理旧 IP 残留: 安装环境 IP 会变, 删除所有旧 dport 5000 的 DNAT(不管旧目标),
        #   再添加当前目标, 避免旧 IP 规则残留劫持流量(PREROUTING + OUTPUT 都清)。
        for _chain in PREROUTING OUTPUT; do
            _h=""
            while read -r _h; do
                [ -n "${_h}" ] || continue
                iptables -t nat -D "${_chain}" ${_h} 2>/dev/null && warn "已删除旧 ${_chain} DNAT: ${_h}"
            done < <(iptables -t nat -L "${_chain}" -n --line-numbers 2>/dev/null \
                        | grep -E "dpt:${EXTERNAL_PORT}.*to:.*:${EXTERNAL_PORT}" \
                        | sed -E 's/^[0-9]+[[:space:]]+//')
        done
        # 1) 立即生效(幂等)
        iptables -t nat -C PREROUTING -d "${HOST_PHYS_IP}" -p tcp --dport "${EXTERNAL_PORT}" -j DNAT --to-destination "${REGISTRY_FORWARD_TARGET}" 2>/dev/null || \
            iptables -t nat -A PREROUTING -d "${HOST_PHYS_IP}" -p tcp --dport "${EXTERNAL_PORT}" -j DNAT --to-destination "${REGISTRY_FORWARD_TARGET}"
        iptables -t nat -C OUTPUT -d "${HOST_PHYS_IP}" -p tcp --dport "${EXTERNAL_PORT}" -j DNAT --to-destination "${REGISTRY_FORWARD_TARGET}" 2>/dev/null || \
            iptables -t nat -A OUTPUT -d "${HOST_PHYS_IP}" -p tcp --dport "${EXTERNAL_PORT}" -j DNAT --to-destination "${REGISTRY_FORWARD_TARGET}"
        ok "iptables DNAT 已就绪(PREROUTING + OUTPUT)"
        # 2) 持久化: forward 脚本 + systemd 单元
        forward_script_body > "${FORWARD_SCRIPT}"
        chmod +x "${FORWARD_SCRIPT}"
        cat > "${UNIT_FILE}" <<EOF
[Unit]
Description=CubeStack internal registry external port forward (${EXTERNAL_PORT} -> ${REGISTRY_FORWARD_TARGET})
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=${FORWARD_SCRIPT} --add
ExecStop=${FORWARD_SCRIPT} --delete

[Install]
WantedBy=multi-user.target
EOF
        systemctl daemon-reload
        systemctl enable "${UNIT}" >/dev/null 2>&1
        systemctl start "${UNIT}" >/dev/null 2>&1 || true
        ok "已安装并启用 systemd 单元 ${UNIT}(重启自动重建)"
        say "集群外 push 用法(需把 ${REGISTRY_DOMAIN:-registry.cubestack.io} 解析到 ${HOST_PHYS_IP}):"
        echo "  docker push ${REGISTRY_DOMAIN:-registry.cubestack.io}:${EXTERNAL_PORT}/<namespace>/<image>:<tag>"
        ;;
    --delete)
        say "删除 registry 端口转发: ${HOST_PHYS_IP}:${EXTERNAL_PORT} → ${REGISTRY_FORWARD_TARGET} ..."
        iptables -t nat -D PREROUTING -d "${HOST_PHYS_IP}" -p tcp --dport "${EXTERNAL_PORT}" -j DNAT --to-destination "${REGISTRY_FORWARD_TARGET}" 2>/dev/null || true
        iptables -t nat -D OUTPUT -d "${HOST_PHYS_IP}" -p tcp --dport "${EXTERNAL_PORT}" -j DNAT --to-destination "${REGISTRY_FORWARD_TARGET}" 2>/dev/null || true
        systemctl disable "${UNIT}" >/dev/null 2>&1 || true
        systemctl stop "${UNIT}" >/dev/null 2>&1 || true
        rm -f "${UNIT_FILE}" "${FORWARD_SCRIPT}"
        systemctl daemon-reload
        ok "已删除 registry 端口转发规则与 systemd 单元"
        ;;
    *)
        err "用法: $0 [--add|--delete]"
        exit 1
        ;;
esac
