#!/bin/bash
# ============================================================
# 宿主机对内置 registry 的对外端口转发管理(集群外 push 用)
# 将 宿主机物理IP:REGISTRY_PORT 的入站流量 DNAT 到 MetalLB VIP(REGISTRY_IP):REGISTRY_PORT,
# 使物理网(10.66.x)上的机器能 docker push registry.local:5000/xxx。
# 同时写 PREROUTING(外部网卡流量) + OUTPUT(宿主机本机 push) 两条规则, 幂等。
# 持久化: 安装 systemd 单元, 重启后自动重建规则。
# 用法: ./setup-registry-expose.sh [--add|--delete]   (默认 --add)
# 数据源: config/cluster.conf (HOST_PHYS_IP / REGISTRY_ENABLED / REGISTRY_IP / REGISTRY_PORT)
# ============================================================
set -euo pipefail

# shellcheck source=lib-common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../lib-common.sh"
load_config

ACTION="${1:---add}"
[ "${REGISTRY_ENABLED:-0}" = "1" ] || { warn "REGISTRY_ENABLED!=1, 跳过端口转发(集群内 registry 默认不部署)"; exit 0; }

# 依据暴露方式决定 DNAT 目标(集群外 push 的落点):
#   loadbalancer → MetalLB 固定 VIP:REGISTRY_PORT
#   nodeport     → 第一个节点的 NodePort(kube-proxy 自动转发到 registry pod, 不依赖 MetalLB)
REGISTRY_FORWARD_TARGET=""
case "${REGISTRY_SERVICE_TYPE:-loadbalancer}" in
    nodeport)
        [ -n "${REGISTRY_NODEPORT:-}" ] || { err "未配置 REGISTRY_NODEPORT"; exit 1; }
        for line in "${NODES[@]:-}"; do
            [ -z "${line}" ] && continue
            IFS=, read -r _r _h ip _rest <<<"${line}"
            [ -n "${ip}" ] && { REGISTRY_FORWARD_TARGET="${ip}:${REGISTRY_NODEPORT}"; break; }
        done
        ;;
    *)
        [ -n "${REGISTRY_IP:-}" ] && [ -n "${REGISTRY_PORT:-}" ] || { err "未配置 REGISTRY_IP/REGISTRY_PORT"; exit 1; }
        REGISTRY_FORWARD_TARGET="${REGISTRY_IP}:${REGISTRY_PORT}"
        ;;
esac
[ -n "${REGISTRY_FORWARD_TARGET}" ] || { err "无法确定 registry 转发目标(检查 REGISTRY_SERVICE_TYPE/NODES)"; exit 1; }
# 外部统一入口端口(集群外 push 用)
EXTERNAL_PORT="${REGISTRY_PORT:-5000}"

# 需 root
[ "$(id -u)" -eq 0 ] || { err "需要 root 权限: sudo $0 ${ACTION}"; exit 1; }

UNIT="cubestack-registry-forward"
UNIT_FILE="/etc/systemd/system/${UNIT}.service"
FORWARD_SCRIPT="/usr/local/bin/${UNIT}.sh"

# 规则体(写入 /usr/local/bin 的 forward 脚本 + systemd 单元引用)
forward_script_body() {
    cat <<EOF
#!/bin/bash
# Auto-generated by setup-registry-expose.sh — 重启后重建 registry 对外 DNAT(勿手工编辑)
# ${HOST_PHYS_IP}:${EXTERNAL_PORT} → ${REGISTRY_FORWARD_TARGET}
set -e
action="\${1:---add}"
if [ "\${action}" = "--delete" ]; then
    iptables -t nat -D PREROUTING -d ${HOST_PHYS_IP} -p tcp --dport ${EXTERNAL_PORT} -j DNAT --to-destination ${REGISTRY_FORWARD_TARGET} 2>/dev/null || true
    iptables -t nat -D OUTPUT -d ${HOST_PHYS_IP} -p tcp --dport ${EXTERNAL_PORT} -j DNAT --to-destination ${REGISTRY_FORWARD_TARGET} 2>/dev/null || true
else
    iptables -t nat -C PREROUTING -d ${HOST_PHYS_IP} -p tcp --dport ${EXTERNAL_PORT} -j DNAT --to-destination ${REGISTRY_FORWARD_TARGET} 2>/dev/null || \
        iptables -t nat -A PREROUTING -d ${HOST_PHYS_IP} -p tcp --dport ${EXTERNAL_PORT} -j DNAT --to-destination ${REGISTRY_FORWARD_TARGET}
    iptables -t nat -C OUTPUT -d ${HOST_PHYS_IP} -p tcp --dport ${EXTERNAL_PORT} -j DNAT --to-destination ${REGISTRY_FORWARD_TARGET} 2>/dev/null || \
        iptables -t nat -A OUTPUT -d ${HOST_PHYS_IP} -p tcp --dport ${EXTERNAL_PORT} -j DNAT --to-destination ${REGISTRY_FORWARD_TARGET}
fi
exit 0
EOF
}

case "${ACTION}" in
    --add)
        say "添加宿主机 registry 端口转发: ${HOST_PHYS_IP}:${EXTERNAL_PORT} → ${REGISTRY_FORWARD_TARGET} ..."
        # 1) 立即生效(幂等)
        iptables -t nat -C PREROUTING -d "${HOST_PHYS_IP}" -p tcp --dport "${EXTERNAL_PORT}" -j DNAT --to-destination "${REGISTRY_FORWARD_TARGET}" 2>/dev/null || \
            iptables -t nat -A PREROUTING -d "${HOST_PHYS_IP}" -p tcp --dport "${EXTERNAL_PORT}" -j DNAT --to-destination "${REGISTRY_FORWARD_TARGET}"
        iptables -t nat -C OUTPUT -d "${HOST_PHYS_IP}" -p tcp --dport "${EXTERNAL_PORT}" -j DNAT --to-destination "${REGISTRY_FORWARD_TARGET}" 2>/dev/null || \
            iptables -t nat -A OUTPUT -d "${HOST_PHYS_IP}" -p tcp --dport "${EXTERNAL_PORT}" -j DNAT --to-destination "${REGISTRY_FORWARD_TARGET}"
        ok "iptables DNAT 已就绪(PREROUTING + OUTPUT)"
        # 2) 持久化: forward 脚本 + systemd 单元
        forward_script_body > "${FORWARD_SCRIPT}"
        chmod +x "${FORWARD_SCRIPT}"
        cat > "${UNIT_FILE}" <<EOF
[Unit]
Description=CubeStack internal registry external port forward (${EXTERNAL_PORT} -> ${REGISTRY_FORWARD_TARGET})
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=${FORWARD_SCRIPT} --add
ExecStop=${FORWARD_SCRIPT} --delete

[Install]
WantedBy=multi-user.target
EOF
        systemctl daemon-reload
        systemctl enable "${UNIT}" >/dev/null 2>&1
        systemctl start "${UNIT}" >/dev/null 2>&1 || true
        ok "已安装并启用 systemd 单元 ${UNIT}(重启自动重建)"
        say "集群外 push 用法(需把 ${REGISTRY_DOMAIN:-registry.local} 解析到 ${HOST_PHYS_IP}):"
        echo "  docker push ${REGISTRY_DOMAIN:-registry.local}:${EXTERNAL_PORT}/<namespace>/<image>:<tag>"
        ;;
    --delete)
        say "删除 registry 端口转发: ${HOST_PHYS_IP}:${EXTERNAL_PORT} → ${REGISTRY_FORWARD_TARGET} ..."
        iptables -t nat -D PREROUTING -d "${HOST_PHYS_IP}" -p tcp --dport "${EXTERNAL_PORT}" -j DNAT --to-destination "${REGISTRY_FORWARD_TARGET}" 2>/dev/null || true
        iptables -t nat -D OUTPUT -d "${HOST_PHYS_IP}" -p tcp --dport "${EXTERNAL_PORT}" -j DNAT --to-destination "${REGISTRY_FORWARD_TARGET}" 2>/dev/null || true
        systemctl disable "${UNIT}" >/dev/null 2>&1 || true
        systemctl stop "${UNIT}" >/dev/null 2>&1 || true
        rm -f "${UNIT_FILE}" "${FORWARD_SCRIPT}"
        systemctl daemon-reload
        ok "已删除 registry 端口转发规则与 systemd 单元"
        ;;
    *)
        err "用法: $0 [--add|--delete]"
        exit 1
        ;;
esac
