#!/bin/bash
# ============================================================
# MODULE: lb_keepalived
# DESC: Keepalived — K8s API VIP 高可用(与 HAProxy 搭配, 集群部署前准备)
# PHASE: env
# DEFAULT: 0
# REPEAT: 1
# TOGGLE: KEEPALIVED_ENABLED
# REQUIRES: lb_haproxy vm_create
# 说明:
#   · 从 cluster.conf 生成 /etc/keepalived/keepalived.conf(VIP = KEEPALIVED_VIP,
#     默认取 APISERVER_ADDRESS), 提供 API 入口 VIP 漂移高可用
#   · 属于环境准备阶段: 在部署 kubespray 之前准备好 API 入口 VIP
#   · 依赖 keepalived 已安装(apt install keepalived); 需 root
#   · 幂等: 每次执行重新收敛 VIP/优先级; 与 lb_haproxy 模块搭配使用
# 数据源: cluster.conf (KEEPALIVED_ENABLED / KEEPALIVED_VIP / APISERVER_ADDRESS / NODES)
# ============================================================
set -euo pipefail

# shellcheck source=lib-common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../lib-common.sh"
load_config

if [ "${KEEPALIVED_ENABLED:-false}" != "true" ]; then
    say "跳过 Keepalived(配置 KEEPALIVED_ENABLED=true 可启用)"
    exit 0
fi
[ "$(id -u)" -eq 0 ] || { err "需要 root: sudo $0"; exit 1; }
command -v keepalived >/dev/null 2>&1 || { err "未安装 keepalived(apt install keepalived)"; exit 1; }

# VIP: 显式 KEEPALIVED_VIP > APISERVER_ADDRESS > 宿主机物理 IP
VIP="${KEEPALIVED_VIP:-${APISERVER_ADDRESS:-${HOST_PHYS_IP}}}"
[ -n "${VIP}" ] || { err "无法确定 VIP(需配置 KEEPALIVED_VIP 或 APISERVER_ADDRESS)"; exit 1; }

# 本机 IP(与 VIP 相同则 MASTER, 否则 BACKUP) — 简单单机场景默认 MASTER
PRIORITY="${KEEPALIVED_PRIORITY:-100}"
IFACE="$(ip route get "${VIP}" 2>/dev/null | grep -oP 'dev \K[^ ]+' | head -1 || echo eth0)"

say "Keepalived VIP: ${VIP}  interface: ${IFACE}  priority: ${PRIORITY}"

# 备份旧配置并生成
[ -f /etc/keepalived/keepalived.conf ] && cp /etc/keepalived/keepalived.conf /etc/keepalived/keepalived.conf.bak-$(date +%Y%m%d%H%M%S) 2>/dev/null || true
mkdir -p /etc/keepalived

cat > /etc/keepalived/keepalived.conf << EOF
# Generated by $(basename "$0") from ${CLUSTER_CONF} — 请勿手工编辑
global_defs {
    router_id cubestack-k8s-api
}

vrrp_instance k8s_api {
    state MASTER
    interface ${IFACE}
    virtual_router_id 51
    priority ${PRIORITY}
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass ${KEEPALIVED_AUTH_PASS:-cubestack}
    }
    virtual_ipaddress {
        ${VIP}
    }
}
EOF

keepalived -t -f /etc/keepalived/keepalived.conf || { err "Keepalived 配置校验失败"; exit 1; }
systemctl restart keepalived
systemctl enable keepalived >/dev/null 2>&1 || true

ok "Keepalived 已更新: VIP ${VIP} @ ${IFACE}"
ip addr show "${IFACE}" 2>/dev/null | grep "${VIP}" || true
