#!/bin/bash
# 从统一配置(config/cluster.conf)生成 kubespray 兼容 inventory
# ============================================================
# 生成:
#   hosts.yml      主清单(kubespray 实际使用; 注意 kubespray ansible.cfg
#                  inventory_ignore_extensions 含 .ini,故 .ini 会被忽略)
#   inventory.ini  兼容 installer 后端(UI)风格的 INI(仅参考/后续UI用)
# 用法: ./gen-inventory.sh                 # 生成全部节点
#       INV_ROLES=master ./gen-inventory.sh # 仅生成控制平面(先部署master,worker后续加入)
# 数据源: config/cluster.conf (NODES / SSH_KEY_NAME / KUBESPRAY_INV_DIR / WORKER_SSH_PASSWORD)
# ============================================================
set -euo pipefail

# shellcheck source=lib-common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib-common.sh"
load_config

INV_DIR="${KUBESPRAY_INV_DIR:-${REPO_ROOT}/deployments/kubespray/inventory/cubestack-cluster}"
mkdir -p "${INV_DIR}"

SSH_KEY_DIR="${SSH_KEY_DIR:-${HOME}/.ssh}"
SSH_KEY_NAME="${SSH_KEY_NAME:-cubestack_k8s}"
SSH_KEY="${SSH_KEY_DIR}/${SSH_KEY_NAME}"

# ---------------- 解析节点 ----------------
# 角色过滤: INV_ROLES="master" 仅生成控制平面; 空=全部
# 排除过滤: INV_EXCLUDE="mxgpu-1-232" 排除指定节点(逗号分隔)
INV_ROLES="${INV_ROLES:-}"
role_included() { # <role> → 0=包含
    [ -z "${INV_ROLES}" ] && return 0
    local r; for r in ${INV_ROLES//,/ }; do [ "$r" = "$1" ] && return 0; done
    return 1
}

node_excluded() { # <hostname> → 0=排除
    [ -z "${INV_EXCLUDE:-}" ] && return 1
    local h; for h in ${INV_EXCLUDE//,/ }; do [ "$h" = "$1" ] && return 0; done
    return 1
}

MASTERS=()   # role,hostname,ip,mac,mem,cpu,disk,user,pw
WORKERS=()
for line in "${NODES[@]:-}"; do
    [ -z "${line}" ] && continue
    IFS=, read -r role hostname ip mac mem cpu disk user pw <<<"${line}"
    role_included "${role}" || continue
    node_excluded "${hostname}" && { warn "排除节点: ${hostname}"; continue; }
    case "${role}" in
        master) MASTERS+=("${line}") ;;
        worker) WORKERS+=("${line}") ;;
        *) warn "未知角色 '${role}',跳过节点 ${hostname}" ;;
    esac
done

# ---------------- 生成 hosts.yml ----------------
HOSTS_YML="${INV_DIR}/hosts.yml"
{
    echo "# Generated by $(basename "$0") from ${CLUSTER_CONF} — 请勿手工编辑"
    echo "all:"
    echo "  vars:"
    echo "    ansible_become: true"
    echo "    ansible_become_method: sudo"
    echo "kube_control_plane:"
    if [ "${#MASTERS[@]}" -gt 0 ]; then
        echo "  hosts:"
        for line in "${MASTERS[@]}"; do
            IFS=, read -r role hostname ip mac mem cpu disk user pw <<<"${line}"
            echo "    ${hostname}:"
            echo "      ansible_host: ${ip}"
            echo "      ip: ${ip}            # K8s 内部通信使用的 IP"
            echo "      access_ip: ${ip}     # API Server 对外暴露的 IP"
            echo "      ansible_user: ${user}"
            echo "      ansible_ssh_private_key_file: ${SSH_KEY}"
        done
    else
        echo "  {}"
    fi
    echo "etcd:"
    echo "  children:"
    echo "    kube_control_plane:"
    echo "kube_node:"
    if [ "${#WORKERS[@]}" -gt 0 ]; then
        echo "  hosts:"
        for line in "${WORKERS[@]}"; do
            IFS=, read -r role hostname ip mac mem cpu disk user pw <<<"${line}"
            node_pw="$(node_password worker "${pw}")"
            echo "    ${hostname}:"
            echo "      ansible_host: ${ip}"
            echo "      ip: ${ip}"
            echo "      access_ip: ${ip}"
            echo "      ansible_user: ${user}"
            # 优先使用密钥认证(免密); 密钥不存在时回退到密码认证
            if [ -f "${SSH_KEY}" ]; then
                echo "      ansible_ssh_private_key_file: ${SSH_KEY}"
            fi
            # 裸金属(物理Worker)用密码认证; 未配置密码则省略(由 kubespray 交互/ssh-agent)
            if [ -n "${node_pw}" ]; then
                echo "      ansible_password: ${node_pw}"
                echo "      ansible_become_password: ${node_pw}"
            else
                echo "      # ansible_password: (未配置 WORKER_SSH_PASSWORD)"
            fi
        done
    else
        echo "  {}"
    fi
    echo "k8s_cluster:"
    echo "  children:"
    echo "    kube_control_plane:"
    echo "    kube_node:"
} > "${HOSTS_YML}"
ok "已生成 hosts.yml: ${HOSTS_YML}"

# ---------------- 生成 inventory.ini(兼容 installer 后端/UI) ----------------
INI="${INV_DIR}/inventory.ini"
{
    echo "# Generated by $(basename "$0") from ${CLUSTER_CONF} — 兼容 installer 后端风格(参考用)"
    echo "# 注意: kubespray 的 ansible.cfg 忽略 .ini,实际部署读取 hosts.yml"
    echo "[all]"
    for line in "${MASTERS[@]}" "${WORKERS[@]}"; do
        IFS=, read -r role hostname ip mac mem cpu disk user pw <<<"${line}"
        echo "${hostname} ansible_host=${ip} ip=${ip}"
    done
    echo ""
    echo "[kube_control_plane]"
    for line in "${MASTERS[@]}"; do
        IFS=, read -r role hostname ip mac mem cpu disk user pw <<<"${line}"
        echo "${hostname}"
    done
    echo ""
    echo "[kube_node]"
    for line in "${WORKERS[@]}"; do
        IFS=, read -r role hostname ip mac mem cpu disk user pw <<<"${line}"
        echo "${hostname}"
    done
    echo ""
    echo "[k8s_cluster:children]"
    echo "kube_control_plane"
    echo "kube_node"
    echo ""
    echo "[all:vars]"
    echo "ansible_become=true"
    echo "ansible_become_user=root"
    echo "ansible_ssh_private_key_file=${SSH_KEY}"
    # 各 worker 的密码(如已配置)
    for line in "${WORKERS[@]}"; do
        IFS=, read -r role hostname ip mac mem cpu disk user pw <<<"${line}"
        node_pw="$(node_password worker "${pw}")"
        if [ -n "${node_pw}" ]; then
            echo ""
            echo "[${hostname}:vars]"
            echo "ansible_user=${user}"
            echo "ansible_password=${node_pw}"
            echo "ansible_become_password=${node_pw}"
        fi
    done
} > "${INI}"
ok "已生成 inventory.ini: ${INI}"

# ---------------- 汇总 ----------------
echo "---------------------------------------------"
[ -n "${INV_ROLES}" ] && echo -e "\033[33m(已按 INV_ROLES=${INV_ROLES} 过滤)\033[0m"
echo -e "\033[36m控制平面(master, 虚拟机):\033[0m ${#MASTERS[@]} 个"
for line in "${MASTERS[@]}"; do
    IFS=, read -r role hostname ip mac mem cpu disk user pw <<<"${line}"
    echo "  ${hostname}  ${ip}  (${mem}G/${cpu}C/${disk}G)"
done
echo -e "\033[36m工作节点(worker, 裸金属):\033[0m ${#WORKERS[@]} 个"
for line in "${WORKERS[@]}"; do
    IFS=, read -r role hostname ip mac mem cpu disk user pw <<<"${line}"
    echo "  ${hostname}  ${ip}"
done
echo "---------------------------------------------"
echo "部署命令参考:"
echo "  ansible-playbook -i ${HOSTS_YML} ${KUBESPRAY_DIR:-<kubespray>}/cluster.yml"

# ---------------- 同步 kubespray 配置(从 cluster.conf 动态生成 IP) ----------------
bash "${SCRIPT_DIR}/sync-kubespray-config.sh"
