#!/bin/bash
# 从统一配置(config/cluster.conf)生成 kubespray 兼容 inventory
# ============================================================
# 生成:
#   hosts.yml      主清单(kubespray 实际使用; 注意 kubespray ansible.cfg
#                  inventory_ignore_extensions 含 .ini,故 .ini 会被忽略)
#   inventory.ini  兼容 installer 后端(UI)风格的 INI(仅参考/后续UI用)
# 用法: ./gen-inventory.sh                 # 生成全部节点
#       INV_ROLES=master ./gen-inventory.sh # 仅生成控制平面(先部署master,worker后续加入)
# 数据源: config/cluster.conf (NODES 5字段: role,hostname,ip,ssh_user,ssh_password / SSH_KEY_NAME / KUBESPRAY_INV_DIR)
# ============================================================
set -euo pipefail

# shellcheck source=lib-common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../lib-common.sh"
load_config

INV_DIR="${KUBESPRAY_INV_DIR:-${REPO_ROOT}/deployments/kubespray/inventory/cubestack-cluster}"
mkdir -p "${INV_DIR}"

SSH_KEY_DIR="${SSH_KEY_DIR:-${HOME}/.ssh}"
SSH_KEY_NAME="${SSH_KEY_NAME:-cubestack_k8s}"
SSH_KEY="${SSH_KEY_DIR}/${SSH_KEY_NAME}"

# ---------------- 解析节点 ----------------
# 角色过滤: INV_ROLES="master" 仅生成控制平面; 空=全部
# 排除过滤: INV_EXCLUDE="mxgpu-1-232" 排除指定节点(逗号分隔)
INV_ROLES="${INV_ROLES:-}"
role_included() { # <role> → 0=包含
    [ -z "${INV_ROLES}" ] && return 0
    local r; for r in ${INV_ROLES//,/ }; do [ "$r" = "$1" ] && return 0; done
    return 1
}

node_excluded() { # <hostname> → 0=排除
    [ -z "${INV_EXCLUDE:-}" ] && return 1
    local h; for h in ${INV_EXCLUDE//,/ }; do [ "$h" = "$1" ] && return 0; done
    return 1
}

MASTERS=()   # 节点行(5字段)
WORKERS=()
for line in "${NODES[@]:-}"; do
    [ -z "${line}" ] && continue
    node_parse "${line}"
    role_included "${NODE_ROLE}" || continue
    node_excluded "${NODE_HOSTNAME}" && { warn "排除节点: ${NODE_HOSTNAME}"; continue; }
    case "${NODE_ROLE}" in
        master) MASTERS+=("${line}") ;;
        worker) WORKERS+=("${line}") ;;
        *) warn "未知角色 '${NODE_ROLE}',跳过节点 ${NODE_HOSTNAME}" ;;
    esac
done

# ---------------- 生成 hosts.yml ----------------
HOSTS_YML="${INV_DIR}/hosts.yml"
# 单节点判定: 仅 1 个 master 且 0 个 worker(= 单节点 all-in-one)。
# 此时让该 master 同时加入 kube_node, 使 kubeadm 模板(kube_control_plane 且 IN kube_node)
# 不给 control-plane 打 NoSchedule 污点 → master 本身可调度(同时是 master+worker)。
SINGLE_NODE=0
if [ "${#MASTERS[@]}" -eq 1 ] && [ "${#WORKERS[@]}" -eq 0 ]; then
    SINGLE_NODE=1
    say "单节点模式: MASTERS=${#MASTERS[@]} WORKERS=${#WORKERS[@]} → 该 master 同时作为 worker(可调度, 无 control-plane 污点)"
fi
{
    echo "# Generated by $(basename "$0") from ${CLUSTER_CONF} — 请勿手工编辑"
    echo "all:"
    echo "  vars:"
    echo "    ansible_become: true"
    echo "    ansible_become_method: sudo"
    echo "kube_control_plane:"
    if [ "${#MASTERS[@]}" -gt 0 ]; then
        echo "  hosts:"
        for line in "${MASTERS[@]}"; do
            node_parse "${line}"
            echo "    ${NODE_HOSTNAME}:"
            echo "      ansible_host: ${NODE_IP}"
            echo "      ip: ${NODE_IP}            # K8s 内部通信使用的 IP"
            echo "      access_ip: ${NODE_IP}     # API Server 对外暴露的 IP"
            echo "      ansible_user: ${NODE_USER}"
            echo "      ansible_ssh_private_key_file: ${SSH_KEY}"
        done
    else
        echo "  {}"
    fi
    echo "etcd:"
    echo "  children:"
    echo "    kube_control_plane:"
    echo "kube_node:"
    # 常规: kube_node = 全部 worker; 单节点模式: 追加该 master, 使其同属 control_plane+kube_node → 可调度
    {
        for line in "${WORKERS[@]}"; do echo "${line}"; done
        [ "${SINGLE_NODE}" = "1" ] && for line in "${MASTERS[@]}"; do echo "${line}"; done
    } > /tmp/gen-inventory-nodes.txt
    if [ -s /tmp/gen-inventory-nodes.txt ]; then
        echo "  hosts:"
        while IFS= read -r line; do
            [ -z "${line}" ] && continue
            node_parse "${line}"
            echo "    ${NODE_HOSTNAME}:"
            echo "      ansible_host: ${NODE_IP}"
            echo "      ip: ${NODE_IP}"
            echo "      access_ip: ${NODE_IP}"
            echo "      ansible_user: ${NODE_USER}"
            # 优先使用密钥认证(免密); 密钥不存在时回退到密码认证
            if [ -f "${SSH_KEY}" ]; then
                echo "      ansible_ssh_private_key_file: ${SSH_KEY}"
            fi
            # 密码认证(节点独立密码或默认密码; 未配置则省略, 由 kubespray 交互/ssh-agent)
            if [ -n "${NODE_PW}" ]; then
                echo "      ansible_password: ${NODE_PW}"
                echo "      ansible_become_password: ${NODE_PW}"
            else
                echo "      # ansible_password: (未配置默认/节点密码)"
            fi
        done < /tmp/gen-inventory-nodes.txt
        rm -f /tmp/gen-inventory-nodes.txt
    else
        rm -f /tmp/gen-inventory-nodes.txt
        echo "  {}"
    fi
    echo "k8s_cluster:"
    echo "  children:"
    echo "    kube_control_plane:"
    echo "    kube_node:"
} > "${HOSTS_YML}"

# ---------------- 生成扩容专用 group(由 SCALE_NODES / SCALE_GROUP_NAME 变量控制) ----------------
# SCALE_NODES: 逗号分隔的 hostname 列表, 仅将这些节点放入扩容组
# SCALE_GROUP_NAME: 扩容组名称, 默认 new_node(可通过 cluster.conf 或环境变量覆盖)
# scale 时 kubespray 自动 --limit 该组, 避免对已有节点重复执行
SCALE_NODES="${SCALE_NODES:-}"
SCALE_GROUP_NAME="${SCALE_GROUP_NAME:-new_node}"
if [ -n "${SCALE_NODES}" ]; then
    {
        echo "${SCALE_GROUP_NAME}:"
        echo "  hosts:"
        for hostname in ${SCALE_NODES//,/ }; do
            hostname="$(echo "${hostname}" | xargs)"  # trim whitespace
            [ -z "${hostname}" ] && continue
            echo "    ${hostname}: {}"
        done
    } >> "${HOSTS_YML}"
    ok "已生成扩容组 ${SCALE_GROUP_NAME}(目标节点: ${SCALE_NODES})"
fi
ok "已生成 hosts.yml: ${HOSTS_YML}"

# ---------------- 生成 inventory.ini(兼容 installer 后端/UI) ----------------
INI="${INV_DIR}/inventory.ini"
{
    echo "# Generated by $(basename "$0") from ${CLUSTER_CONF} — 兼容 installer 后端风格(参考用)"
    echo "# 注意: kubespray 的 ansible.cfg 忽略 .ini,实际部署读取 hosts.yml"
    echo "[all]"
    for line in "${MASTERS[@]}" "${WORKERS[@]}"; do
        node_parse "${line}"
        echo "${NODE_HOSTNAME} ansible_host=${NODE_IP} ip=${NODE_IP}"
    done
    echo ""
    echo "[kube_control_plane]"
    for line in "${MASTERS[@]}"; do
        node_parse "${line}"
        echo "${NODE_HOSTNAME}"
    done
    echo ""
    echo "[kube_node]"
    for line in "${WORKERS[@]}"; do
        node_parse "${line}"
        echo "${NODE_HOSTNAME}"
    done
    echo ""
    echo "[k8s_cluster:children]"
    echo "kube_control_plane"
    echo "kube_node"
    echo ""
    echo "[all:vars]"
    echo "ansible_become=true"
    echo "ansible_become_user=root"
    echo "ansible_ssh_private_key_file=${SSH_KEY}"
    # 各 worker 的密码(节点独立密码或默认密码)
    for line in "${WORKERS[@]}"; do
        node_parse "${line}"
        if [ -n "${NODE_PW}" ]; then
            echo ""
            echo "[${NODE_HOSTNAME}:vars]"
            echo "ansible_user=${NODE_USER}"
            echo "ansible_password=${NODE_PW}"
            echo "ansible_become_password=${NODE_PW}"
        fi
    done
} > "${INI}"
ok "已生成 inventory.ini: ${INI}"

# ---------------- 汇总 ----------------
echo "---------------------------------------------"
[ -n "${INV_ROLES}" ] && echo -e "\033[33m(已按 INV_ROLES=${INV_ROLES} 过滤)\033[0m"
echo -e "\033[36m控制平面(master):\033[0m ${#MASTERS[@]} 个"
for line in "${MASTERS[@]}"; do
    node_parse "${line}"
    echo "  ${NODE_HOSTNAME}  ${NODE_IP}  (user=${NODE_USER})"
done
echo -e "\033[36m工作节点(worker):\033[0m ${#WORKERS[@]} 个"
for line in "${WORKERS[@]}"; do
    node_parse "${line}"
    echo "  ${NODE_HOSTNAME}  ${NODE_IP}  (user=${NODE_USER})"
done
echo "---------------------------------------------"
echo "部署命令参考:"
echo "  ansible-playbook -i ${HOSTS_YML} ${KUBESPRAY_DIR:-<kubespray>}/cluster.yml"

# ---------------- 同步 kubespray 配置(从 cluster.conf 动态生成 IP) ----------------
bash "${SCRIPT_DIR}/tools/k8s/sync-kubespray-config.sh"
