# Copyright Envoy AI Gateway Authors
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

{{- if .Values.controller.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ai-gateway-helm.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-gateway-helm.labels" . | nindent 4 }}
  {{- with .Values.controller.podDisruptionBudget.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if hasKey .Values.controller.podDisruptionBudget "maxUnavailable" }}
  maxUnavailable: {{ .Values.controller.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.controller.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ai-gateway-helm.controller.selectorLabels" . | nindent 6 }}
{{- end }}
